[workspace]
# mox: when holt_backend=icloud
backend   = "icloud"
# mox: end
# mox: when holt_backend=gdrive
backend   = "gdrive"
# mox: end
# mox: when not holt_backend=icloud and not holt_backend=gdrive
synced_root = "~/workspace"
# mox: end
code_root = "~/Code"
hub_root  = "~/Projects"

# mox: when holt_backend=icloud
[backends.icloud]
synced_root = "~/Library/Mobile Documents/com~apple~CloudDocs/workspace"
# mox: end
# mox: when holt_backend=gdrive
[backends.gdrive]
synced_root = "~/Library/CloudStorage/GoogleDrive-<machine.gdrive_account>/マイドライブ/workspace"
# mox: end
