#!/usr/bin/env zsh
local cmdHash="nohash" data="$*" name

for name in $@; do
  if [ "${name}" = "${name#[A-Za-z_][A-Za-z0-9_]*=}" ]; then
    break
  fi
done

if typeset -f "${name}" > /dev/null; then
  data=${data}$(typeset -f "${name}")
fi

if builtin command -v md5 > /dev/null; then
  cmdHash=$(echo -n "${data}" | md5)
elif builtin command -v md5sum > /dev/null; then
  cmdHash=$(echo -n "${data}" | md5sum | cut -d' ' -f1)
fi

local cacheFile="$ZSH_EVALCACHE_DIR/init-${name##*/}-${cmdHash}.sh"

if [ "$ZSH_EVALCACHE_DISABLE" = "true" ]; then
  eval ${(q)@}
elif [ -s "$cacheFile" ]; then
  source "$cacheFile"
else
  if type "${name}" > /dev/null; then
    echo "evalcache: ${name} initialization not cached, caching output of: $*" >&2
    mkdir -p "$ZSH_EVALCACHE_DIR"
    eval ${(q)@} > "$cacheFile"
    source "$cacheFile"
  else
    echo "evalcache: ERROR: ${name} is not installed or in PATH" >&2
  fi
fi
