return {
  dap = {
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
  },
  diagnostics = {
    Error = " ",
    Hint = " ",
    Info = " ",
    Warn = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  status = {
    Lsp = " ",
    Vim = " ",
    Mode = " ",
    Lock = " ",
    Debug = " ",
    Directory = " ",
    DirectoryAlt = "󰉖 ",
    Ellipsis = "…",
  },
}
