local T = require("tests.helpers")

local function sh(cmd) return vim.fn.system(cmd) end

local function make_fixture()
  local dir = vim.fn.tempname()
  vim.fn.mkdir(dir, "p")
  sh({ "git", "-C", dir, "init", "-q", "-b", "main" })
  sh({ "git", "-C", dir, "config", "user.email", "t@t.t" })
  sh({ "git", "-C", dir, "config", "user.name", "t" })
  vim.fn.writefile({ "1" }, dir .. "/f.txt")
  sh({ "git", "-C", dir, "add", "f.txt" })
  sh({ "git", "-C", dir, "commit", "-q", "-m", "first" })
  sh({ "git", "-C", dir, "tag", "v1.0.0" })
  vim.fn.writefile({ "2" }, dir .. "/f.txt")
  sh({ "git", "-C", dir, "commit", "-q", "-am", "second" })
  return dir
end

local function fresh() package.loaded["core.pack.git"] = nil; return require("core.pack.git") end

T.describe("core.pack.git", function()
  T.it("is_repo true on a git dir, false otherwise", function()
    local G = fresh()
    local fix = make_fixture()
    T.truthy(G.is_repo(fix))
    T.eq(G.is_repo(vim.fn.tempname()), false)
  end)

  T.it("current_rev returns a 40-char sha", function()
    local G = fresh()
    local fix = make_fixture()
    local rev = G.current_rev(fix)
    T.truthy(rev and #rev == 40)
  end)

  T.it("clone creates a working copy with HEAD", function()
    local G = fresh()
    local src = make_fixture()
    local dest = vim.fn.tempname()
    local r = G.clone("file://" .. src, dest)
    T.eq(r.ok, true, r.err)
    T.truthy(G.current_rev(dest))
  end)

  T.it("checkout switches to a tag", function()
    local G = fresh()
    local src = make_fixture()
    local dest = vim.fn.tempname()
    G.clone("file://" .. src, dest)
    local r = G.checkout(dest, "v1.0.0")
    T.eq(r.ok, true, r.err)
  end)

  T.it("log_between returns commit list between revs", function()
    local G = fresh()
    local src = make_fixture()
    local dest = vim.fn.tempname()
    G.clone("file://" .. src, dest)
    G.checkout(dest, "v1.0.0")
    local v1 = G.current_rev(dest)
    G.checkout(dest, "main")
    local head = G.current_rev(dest)
    local commits = G.log_between(dest, v1, head)
    T.truthy(commits and #commits >= 1)
    T.truthy(commits[1].sha and commits[1].subject)
  end)

  T.it("list_remote_refs returns tags and branches", function()
    local G = fresh()
    local src = make_fixture()
    local dest = vim.fn.tempname()
    G.clone("file://" .. src, dest)
    local refs = G.list_remote_refs(dest)
    T.truthy(vim.tbl_contains(refs.tags, "v1.0.0"))
    T.truthy(vim.tbl_contains(refs.branches, "main"))
  end)

  T.it("default_branch resolves to 'main' for the fixture", function()
    local G = fresh()
    local src = make_fixture()
    local dest = vim.fn.tempname()
    G.clone("file://" .. src, dest)
    T.eq(G.default_branch(dest), "main")
  end)
end)
