-- tests/pack/spec_spec.lua
local T = require("tests.helpers")
local F = require("tests.pack.fixtures")

local function reset_spec()
  package.loaded["core.pack.spec"] = nil
  return require("core.pack.spec")
end

T.describe("core.pack.spec._merge: collections", function()
  T.it("dependencies: union, dedup", function()
    local Spec = reset_spec()
    local a = Spec.normalize(F.with_deps("p", { "x", "y" }))
    local b = Spec.normalize(F.with_deps("p", { "y", "z" }))
    local merged = Spec._merge(a, b)
    table.sort(merged.dependencies)
    T.eq(merged.dependencies, { "x", "y", "z" })
  end)

  T.it("opts: deep merge with later overriding nested values", function()
    local Spec = reset_spec()
    local a = Spec.normalize(F.with_opts("p", { ui = { width = 10, height = 20 }, debug = false }))
    local b = Spec.normalize(F.with_opts("p", { ui = { width = 30 }, extra = true }))
    local merged = Spec._merge(a, b)
    T.eq(merged.opts.ui.width, 30)
    T.eq(merged.opts.ui.height, 20)
    T.eq(merged.opts.debug, false)
    T.eq(merged.opts.extra, true)
  end)

  T.it("keys: union by lhs+mode, later additions appended", function()
    local Spec = reset_spec()
    local k1 = { "<F60>", function() end, mode = "n", desc = "a" }
    local k2 = { "<F61>", function() end, mode = "n", desc = "b" }
    local a = Spec.normalize({ dev = true, name = "p", keys = { k1 } })
    local b = Spec.normalize({ dev = true, name = "p", keys = { k2 } })
    local merged = Spec._merge(a, b)
    T.eq(#merged.keys, 2)
  end)

  T.it("event: union of strings", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", event = "BufRead" })
    local b = Spec.normalize({ dev = true, name = "p", event = { "BufWrite", "BufRead" } })
    local merged = Spec._merge(a, b)
    table.sort(merged.event)
    T.eq(merged.event, { "BufRead", "BufWrite" })
  end)

  T.it("ft: union of strings", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", ft = "lua" })
    local b = Spec.normalize({ dev = true, name = "p", ft = { "lua", "vim" } })
    local merged = Spec._merge(a, b)
    table.sort(merged.ft)
    T.eq(merged.ft, { "lua", "vim" })
  end)

  T.it("cmd: union of strings", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", cmd = "Foo" })
    local b = Spec.normalize({ dev = true, name = "p", cmd = { "Bar", "Foo" } })
    local merged = Spec._merge(a, b)
    table.sort(merged.cmd)
    T.eq(merged.cmd, { "Bar", "Foo" })
  end)
end)

T.describe("core.pack.spec._merge: boolean-style fields", function()
  T.it("priority: max", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", priority = 50 })
    local b = Spec.normalize({ dev = true, name = "p", priority = 100 })
    T.eq(Spec._merge(a, b).priority, 100)
    T.eq(Spec._merge(b, a).priority, 100)  -- order-independent
  end)

  T.it("lazy: any non-lazy → eager", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", lazy = true })
    local b = Spec.normalize({ dev = true, name = "p", lazy = false })
    T.eq(Spec._merge(a, b).lazy, false)
    T.eq(Spec._merge(b, a).lazy, false)
  end)

  T.it("enabled: any disabled → disabled", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = true, name = "p", enabled = true })
    local b = Spec.normalize({ dev = true, name = "p", enabled = false })
    T.eq(Spec._merge(a, b).enabled, false)
    T.eq(Spec._merge(b, a).enabled, false)
  end)

  T.it("dev: any dev → dev", function()
    local Spec = reset_spec()
    local a = Spec.normalize({ dev = false, src = "https://x/y", name = "p" })
    local b = Spec.normalize({ dev = true, name = "p" })
    T.eq(Spec._merge(a, b).dev, true)
    T.eq(Spec._merge(b, a).dev, true)
  end)
end)
