local T = require("tests.helpers")
local C = require("lib.colors.color")
local H = require("lib.colors.harmony")

T.describe("lib.colors.harmony", function()
  T.it("complementary rotates hue by 180°", function()
    local red = C.from_oklch(0.6, 0.1, 30)
    local comp = H.complementary(red)
    local _, _, h = C.to_oklch(comp)
    T.truthy(math.abs(h - 210) < 1, "expected ~210, got " .. h)
  end)

  T.it("triad returns two colors at +120° and +240°", function()
    local red = C.from_oklch(0.6, 0.1, 30)
    local a, b = H.triad(red)
    local _, _, ha = C.to_oklch(a)
    local _, _, hb = C.to_oklch(b)
    T.truthy(math.abs(ha - 150) < 1, "ha ~150, got " .. ha)
    T.truthy(math.abs(hb - 270) < 1, "hb ~270, got " .. hb)
  end)

  T.it("analogous returns two colors at ±30°", function()
    local c = C.from_oklch(0.6, 0.1, 100)
    local a, b = H.analogous(c)
    local _, _, ha = C.to_oklch(a)
    local _, _, hb = C.to_oklch(b)
    T.truthy(math.abs(ha - 70) < 1,  "ha ~70, got "  .. ha)
    T.truthy(math.abs(hb - 130) < 1, "hb ~130, got " .. hb)
  end)
end)

T.describe("lib.colors.harmony nearest", function()
  T.it("nearest_tailwind returns red-NNN for a red-ish color", function()
    local c = C.from_hex("#ef4444")  -- close to v4 red-500
    local name, dist = H.nearest_tailwind(c)
    T.truthy(name == "red-500" or name:match("^red%-"),
      "expected red-NNN, got " .. tostring(name))
    T.truthy(dist < 0.05, "expected small distance, got " .. tostring(dist))
  end)

  T.it("nearest_named returns 'red' for #ff0000", function()
    local c = C.from_hex("#ff0000")
    local name = H.nearest_named(c)
    T.eq(name, "red")
  end)
end)
