local T = require("tests.helpers")
local C = require("lib.colors.color")
local H = require("lib.colors.harmony")

T.describe("lib.colors.harmony", function()
  T.it("complementary rotates hue by 180°", function()
    local red = C.from_oklch(0.6, 0.2, 30)
    local comp = H.complementary(red)
    local _, _, h = C.to_oklch(comp)
    T.truthy(math.abs(h - 210) < 1, "expected ~210, got " .. h)
  end)

  T.it("triad returns two colors at +120° and +240°", function()
    local red = C.from_oklch(0.6, 0.2, 30)
    local a, b = H.triad(red)
    local _, _, ha = C.to_oklch(a)
    local _, _, hb = C.to_oklch(b)
    T.truthy(math.abs(ha - 150) < 1, "ha ~150, got " .. ha)
    T.truthy(math.abs(hb - 270) < 1, "hb ~270, got " .. hb)
  end)

  T.it("analogous returns two colors at ±30°", function()
    local c = C.from_oklch(0.6, 0.2, 100)
    local a, b = H.analogous(c)
    local _, _, ha = C.to_oklch(a)
    local _, _, hb = C.to_oklch(b)
    T.truthy(math.abs(ha - 70) < 1,  "ha ~70, got "  .. ha)
    T.truthy(math.abs(hb - 130) < 1, "hb ~130, got " .. hb)
  end)
end)
