local T = require("tests.helpers")
local P = require("lib.colors.parse")

T.describe("lib.colors.parse hex", function()
  T.it("parse identifies hex literal at offset", function()
    local r = P.parse("color: #ff8800;", 8)
    T.truthy(r, "expected a result")
    T.eq(r.range.col_s, 7)   -- 0-indexed start of "#ff8800"
    T.eq(r.range.col_e, 14)  -- exclusive end
    T.eq(r.color.source.fmt, "hex")
  end)

  T.it("parse_all finds multiple hex literals on a line", function()
    local results = P.parse_all("a: #f00; b: #00ff00ff; c: #fff;")
    T.eq(#results, 3)
    T.eq(results[1].color.source.fmt, "hex")
    T.eq(results[2].color.source.fmt, "hex")
    T.eq(results[3].color.source.fmt, "hex")
  end)

  T.it("parse_all returns empty for no colors", function()
    local results = P.parse_all("just plain text")
    T.eq(#results, 0)
  end)
end)

T.describe("lib.colors.parse rgb/rgba", function()
  T.it("parses legacy rgb(255, 136, 0)", function()
    local r = P.parse_all("c: rgb(255, 136, 0);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.01)
    T.truthy(math.abs(r[1].color.g - 136/255) < 0.01)
    T.truthy(math.abs(r[1].color.b - 0) < 0.01)
  end)

  T.it("parses modern rgb(255 136 0)", function()
    local r = P.parse_all("c: rgb(255 136 0);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.01)
  end)

  T.it("parses rgba with alpha", function()
    local r = P.parse_all("c: rgba(255, 0, 0, 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)

  T.it("parses rgb with / alpha (modern)", function()
    local r = P.parse_all("c: rgb(255 0 0 / 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)
end)

T.describe("lib.colors.parse hsl/hsla", function()
  T.it("parses hsl(0, 100%, 50%) as red", function()
    local r = P.parse_all("c: hsl(0, 100%, 50%);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1) < 0.01, "r near 1")
    T.truthy(math.abs(r[1].color.g - 0) < 0.01, "g near 0")
    T.truthy(math.abs(r[1].color.b - 0) < 0.01, "b near 0")
  end)

  T.it("parses modern hsl(120 100% 50%)", function()
    local r = P.parse_all("c: hsl(120 100% 50%);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.g - 1) < 0.01, "g near 1 for green")
  end)

  T.it("parses hsla with alpha", function()
    local r = P.parse_all("c: hsla(0, 100%, 50%, 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)
end)

T.describe("lib.colors.parse oklch", function()
  T.it("parses oklch(0.74 0.16 50)", function()
    local r = P.parse_all("c: oklch(0.74 0.16 50);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.05)
    T.truthy(r[1].color.source.fmt == "oklch")
  end)

  T.it("parses oklch with percent lightness", function()
    local r = P.parse_all("c: oklch(74% 0.16 50);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.05)
  end)

  T.it("parses oklch with / alpha", function()
    local r = P.parse_all("c: oklch(0.74 0.16 50 / 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)
end)

T.describe("lib.colors.parse named", function()
  T.it("parses 'red' to #ff0000", function()
    local r = P.parse_all("color: red;")
    T.eq(#r, 1)
    T.eq(r[1].color.r, 1)
    T.eq(r[1].color.g, 0)
    T.eq(r[1].color.b, 0)
    T.eq(r[1].color.source.fmt, "named")
  end)

  T.it("parses 'darkorange' as separate token", function()
    local r = P.parse_all("color: darkorange;")
    T.eq(#r, 1)
  end)

  T.it("does NOT parse 'red' inside an identifier", function()
    local r = P.parse_all("border-radius: 4px;")
    T.eq(#r, 0)
  end)
end)

T.describe("lib.colors.parse oklab", function()
  T.it("parses oklab(0.74 0.1 0.12)", function()
    local r = P.parse_all("c: oklab(0.74 0.1 0.12);")
    T.eq(#r, 1)
    T.truthy(r[1].color.source.fmt == "oklab")
    -- Should produce a non-grey srgb color
    T.truthy(r[1].color.r ~= r[1].color.g or r[1].color.g ~= r[1].color.b,
      "expected chromatic, got grey")
  end)

  T.it("parses oklab with percent lightness", function()
    local r = P.parse_all("c: oklab(74% 0.1 0.12);")
    T.eq(#r, 1)
  end)

  T.it("parses oklab with / alpha", function()
    local r = P.parse_all("c: oklab(0.5 0.05 0.05 / 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)
end)

T.describe("lib.colors.parse tailwind classes", function()
  T.it("parses bg-red-500 as the Tailwind palette color", function()
    local r = P.parse_all([[<div class="bg-red-500">]])
    T.eq(#r, 1)
    T.truthy(r[1].color.source.tailwind_class == "red-500")
  end)

  T.it("parses bg-[#abc] arbitrary value", function()
    local r = P.parse_all([[<div class="bg-[#abc]">]])
    T.eq(#r, 1)
    T.eq(r[1].color.source.fmt, "hex")
  end)

  T.it("parses bg-[oklch(0.74_0.16_50)] arbitrary oklch", function()
    local r = P.parse_all([[<div class="bg-[oklch(0.74_0.16_50)]">]])
    T.eq(#r, 1)
    T.eq(r[1].color.source.fmt, "oklch")
  end)
end)
