local T = require("tests.helpers")
local P = require("lib.colors.parse")

T.describe("lib.colors.parse hex", function()
  T.it("parse identifies hex literal at offset", function()
    local r = P.parse("color: #ff8800;", 8)
    T.truthy(r, "expected a result")
    T.eq(r.range.col_s, 7)   -- 0-indexed start of "#ff8800"
    T.eq(r.range.col_e, 14)  -- exclusive end
    T.eq(r.color.source.fmt, "hex")
  end)

  T.it("parse_all finds multiple hex literals on a line", function()
    local results = P.parse_all("a: #f00; b: #00ff00ff; c: #fff;")
    T.eq(#results, 3)
    T.eq(results[1].color.source.fmt, "hex")
    T.eq(results[2].color.source.fmt, "hex")
    T.eq(results[3].color.source.fmt, "hex")
  end)

  T.it("parse_all returns empty for no colors", function()
    local results = P.parse_all("just plain text")
    T.eq(#results, 0)
  end)
end)

T.describe("lib.colors.parse rgb/rgba", function()
  T.it("parses legacy rgb(255, 136, 0)", function()
    local r = P.parse_all("c: rgb(255, 136, 0);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.01)
    T.truthy(math.abs(r[1].color.g - 136/255) < 0.01)
    T.truthy(math.abs(r[1].color.b - 0) < 0.01)
  end)

  T.it("parses modern rgb(255 136 0)", function()
    local r = P.parse_all("c: rgb(255 136 0);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.r - 1.0) < 0.01)
  end)

  T.it("parses rgba with alpha", function()
    local r = P.parse_all("c: rgba(255, 0, 0, 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)

  T.it("parses rgb with / alpha (modern)", function()
    local r = P.parse_all("c: rgb(255 0 0 / 0.5);")
    T.eq(#r, 1)
    T.truthy(math.abs(r[1].color.a - 0.5) < 0.01)
  end)
end)
