local T = require("tests.helpers")
local P = require("lib.colors.picker")
local C = require("lib.colors.color")

T.describe("lib.colors.picker state", function()
  T.it("open creates a state with current color", function()
    local s = P.open({ initial = C.from_hex("#ff0000") })
    T.truthy(s)
    T.eq(s.color.r, 1)
    T.eq(s.color.g, 0)
    T.eq(s.color.b, 0)
    T.eq(s.mode, "compact")
    T.eq(s.space, "rgb")
    P.close(s)
  end)

  T.it("close marks state as closed", function()
    local s = P.open({ initial = C.from_hex("#00ff00") })
    P.close(s)
    T.eq(s.mode, "closed")
  end)

  T.it("toggle_expand cycles compact ↔ expanded", function()
    local s = P.open({ initial = C.from_hex("#0000ff") })
    P.toggle_expand(s)
    T.eq(s.mode, "expanded")
    P.toggle_expand(s)
    T.eq(s.mode, "compact")
    P.close(s)
  end)
end)
