;;; autoload/company-box.el -*- lexical-binding: t; -*-

;;;###autoload
(defun +company-box--compute-frame-position-a (frame)
  (-let* ((window-configuration-change-hook nil)
          ((left top _right _bottom) (company-box--edges))
          (window-tab-line-height (if (fboundp 'window-tab-line-height)
                                      (window-tab-line-height)
                                    0))
          (top (+ top window-tab-line-height))
          (char-height (line-pixel-height))
          (char-width (frame-char-width frame))
          (height (* (min company-candidates-length company-tooltip-limit) char-height))
          (space-numbers (if (eq company-show-quick-access 'left) char-width 0))
          (frame-resize-pixelwise t)
          (mode-line-y (company-box--point-bottom))
          ((p-x . p-y) (company-box--prefix-pos))
          (p-y-abs (+ top p-y))
          (y (or (and (> p-y-abs (/ mode-line-y 2))
                      (<= (- mode-line-y p-y) (+ char-height height))
                      (> (- p-y-abs height) 0)
                      (- p-y height))
                 (+ p-y char-height)))
          (height (or (and (> y p-y)
                           (> height (- mode-line-y y))
                           (- mode-line-y y))
                      height))
          (height (- height (mod height char-height)))
          (scrollbar-width (if (eq company-box-scrollbar 'left) (frame-scroll-bar-width frame) 0))
          (x (if (eq company-box-frame-behavior 'point)
                 p-x
               (if company-box--with-icons-p
                   (- p-x (* char-width (if (= company-box--space 2) 2 3)) space-numbers scrollbar-width)
                 (- p-x (if (= company-box--space 0) 0 char-width) space-numbers scrollbar-width)))))
    (setq company-box--x (max (+ x left) 0)
          company-box--top (+ y top)
          company-box--height height
          company-box--chunk-size (/ height char-height))
    (with-current-buffer (company-box--get-buffer)
      (setq company-box--x (max (+ x left) 0)
            company-box--top (+ y top)
            company-box--height height
            company-box--chunk-size (/ height char-height)))))
