[tools]
node = "latest"
python = "latest"
ruby = "latest"
php = "latest"
zig = "latest"
usage = "latest"
# mox: when os=linux
rust = "latest"
# mox: end

[settings]
experimental = true
# mox: when profile=work
idiomatic_version_file_enable_tools = ["ruby"]
# mox: end

